// Publishes an already-built R2R portfolio (narrative + project descriptions)
// as a GitHub repo of markdown — the other Portfolioforge capability, ported
// per the M47.1 decision: reuse the logged-in user's own GitHub OAuth token
// (already has `repo` scope) instead of Portfolioforge's separate, now-
// retired OAuth flow / static PAT.
//
// This is a ONE-WAY terminal export: portfolio -> repo. The created repo is
// tagged with GENERATED_PORTFOLIO_TOPIC (must match routes/repos.js's
// constant) so it can never be re-imported as if it were a source project —
// that round-trip is exactly the bug this session found and fixed (M47.3/M48).
const axios = require('axios');

const GITHUB_API = 'https://api.github.com';
const GENERATED_PORTFOLIO_TOPIC = 'repo2reputation-generated';

function headers(token) {
  return {
    'User-Agent': 'Repo2Reputation/1.0',
    'Accept': 'application/vnd.github.v3+json',
    Authorization: `token ${token}`,
  };
}

async function ensureRepoExists(token, owner, repoName) {
  try {
    const { data } = await axios.get(`${GITHUB_API}/repos/${owner}/${repoName}`, { headers: headers(token) });
    return { created: false, repo: data };
  } catch (err) {
    if (err.response?.status !== 404) throw err;
  }
  const { data } = await axios.post(
    `${GITHUB_API}/user/repos`,
    { name: repoName, description: 'Portfolio generated by Repo2Reputation', private: false, auto_init: true },
    { headers: headers(token) }
  );
  return { created: true, repo: data };
}

async function setGeneratedTopic(token, owner, repoName, existingTopics = []) {
  const topics = [...new Set([...existingTopics, GENERATED_PORTFOLIO_TOPIC])];
  await axios.put(
    `${GITHUB_API}/repos/${owner}/${repoName}/topics`,
    { names: topics },
    { headers: { ...headers(token), Accept: 'application/vnd.github.mercy-preview+json' } }
  );
}

async function upsertFile(token, owner, repoName, path, content, message) {
  let sha;
  try {
    const { data } = await axios.get(`${GITHUB_API}/repos/${owner}/${repoName}/contents/${path}`, { headers: headers(token) });
    sha = data.sha;
  } catch (err) {
    if (err.response?.status !== 404) throw err;
  }
  await axios.put(
    `${GITHUB_API}/repos/${owner}/${repoName}/contents/${path}`,
    { message, content: Buffer.from(content, 'utf8').toString('base64'), ...(sha ? { sha } : {}) },
    { headers: headers(token) }
  );
}

function buildPortfolioReadme(narrative, profile) {
  const skillsList = (narrative.top_skills || []).map(s => `\`${s.name}\``).join(' · ') || '_None yet_';
  const projectLinks = (narrative.projects || [])
    .map((p, i) => `- [${p.repoName}](./project-${i + 1}/README.md)`)
    .join('\n') || '_No projects yet_';

  return `# ${profile?.name || 'Portfolio'}
${narrative.headline ? `\n**${narrative.headline}**\n` : ''}
## About

${narrative.narrative || ''}

## Skills & Tools

${skillsList}

## Projects

${projectLinks}

---
_Generated by Repo2Reputation._
`;
}

function buildProjectReadme(project) {
  return `# ${project.repoName}

${project.description || project.oneLiner || ''}
`;
}

// narrative: portfolio.content_json.narrative (headline, narrative, top_skills, projects[])
// profile:   portfolio.content_json.profile
async function publishPortfolioAsGithubRepo({ token, owner, repoName, narrative, profile }) {
  const { repo, created } = await ensureRepoExists(token, owner, repoName);
  await setGeneratedTopic(token, owner, repoName, repo.topics || []);

  await upsertFile(token, owner, repoName, 'README.md', buildPortfolioReadme(narrative, profile), 'Update portfolio README');

  const projects = narrative.projects || [];
  for (let i = 0; i < projects.length; i++) {
    await upsertFile(
      token, owner, repoName, `project-${i + 1}/README.md`,
      buildProjectReadme(projects[i]),
      `Update project-${i + 1} README`
    );
  }

  return { repoUrl: repo.html_url || `https://github.com/${owner}/${repoName}`, created };
}

module.exports = { publishPortfolioAsGithubRepo, GENERATED_PORTFOLIO_TOPIC };
